# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b425c7722e5af7e0e0ea73b90aa4bc19a793c60506071be1231467a3ff25f459407e08782c4f761e3f90c3ef03c7f19151f57f2bab6d6380ff55168cf194ef

test:
  secret_key_base: 754c05bc3d1cf20ca4684d832aeaf21b23bd09a5592f8ff01493c72ca23aaf88f2838d2b8ef75d18e18796545fcb45132d5c929d08dbcb5bb577d58361025a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
